pipeline {
    agent any

    stages {
        stage('Pull latest code') {
            steps {
                git branch: 'main', url: 'git@github.com:bhatadarsh/jenkins_task.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                cd flask-backend
                echo "Creating venv if not exists..."
                [ ! -d venv ] && python3 -m venv venv
                echo "Activating venv..."
                . venv/bin/activate
                echo "Upgrading pip and installing dependencies..."
                pip install --upgrade pip --break-system-packages
                pip install -r requirements.txt --break-system-packages
                '''
            }
        }

        stage('Restart Flask service') {
            steps {
                sh '''
                cd flask-backend
                echo "Restarting Flask service with PM2..."
                pm2 delete flask-app || true
                pm2 start venv/bin/gunicorn --name flask-app -- \
                    --bind 0.0.0.0:5000 wsgi:app
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
