pipeline {
    agent any

    stages {
        stage('Pull latest code') {
            steps {
                git branch: 'main', url: 'git@github.com:bhatadarsh/jenkins_task.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                cd flask-backend
                if [ ! -d "venv" ]; then
                    python3 -m venv venv
                fi
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Restart Flask service') {
            steps {
                sh '''
                pm2 restart flask-app || pm2 start venv/bin/gunicorn --name flask-app --bind 0.0.0.0:5000 wsgi:app
                pm2 save
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Flask app deployed successfully!"
        }
        failure {
            echo "❌ Deployment failed!"
        }
    }
}

