pipeline {
    agent any

    stages {
        stage('Pull latest code') {
            steps {
                git branch: 'main', url: 'git@github.com:bhatadarsh/jenkins_task.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    cd flask-backend
                    echo "Creating venv if not exists..."
                    if [ ! -d venv ]; then
                        python3 -m venv venv
                    fi
                    echo "Activating venv..."
                    . venv/bin/activate
                    echo "Upgrading pip and installing dependencies..."
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Restart Flask service') {
            steps {
                sh '''
                    cd flask-backend
                    echo "Restarting Flask app with PM2..."
                    pm2 delete flask-app || true
                    pm2 start venv/bin/gunicorn --name flask-app -- \
                        --bind 0.0.0.0:5000 wsgi:app
                    pm2 save
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Flask backend deployed successfully!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
